# Generated by Django 5.1.4 on 2025-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobpost_companyname_jobpost_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.TextField(),
        ),
    ]
