# Generated by Django 5.1.4 on 2025-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='accounts.jobpost'),
        ),
    ]
