# Generated by Django 5.1.4 on 2025-01-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
